fluidtruck/helm-charts

.github/workflows/lint-test.yml
.github/workflows/linter.yml
.github/workflows/release.yml
.github/workflows/validate-pr.yml
CODEOWNERS
charts/golang/.helmignore
charts/golang/Chart.lock
charts/golang/Chart.yaml
charts/golang/README.md
charts/golang/ci/default-values.yaml
charts/golang/ci/with-envvars-values.yaml
charts/golang/ci/with-hpa-values.yaml
charts/golang/ci/with-ingress-values.yaml
charts/golang/ci/with-lifecyle-values.yaml
charts/golang/ci/with-postgresql-values.yaml
charts/golang/ci/with-redis.yaml
charts/golang/templates/NOTES.txt
charts/golang/templates/_helpers.tpl
charts/golang/templates/deployment.yaml
charts/golang/templates/frontendconfig-force-https.yaml
charts/golang/templates/hpa.yaml
charts/golang/templates/ingress.yaml
charts/golang/templates/postgresql/wait-for-postgresql.yaml
charts/golang/templates/redis/wait-for-redis.yaml
charts/golang/templates/service.yaml
charts/golang/values.yaml

Adds the `golang` Helm chart with basic testing in place.

[golang] initial release :tada

---

charts/locust/.helmignore
charts/locust/Chart.lock
charts/locust/Chart.yaml
charts/locust/ci/default-values.yaml
charts/locust/ci/with-master-ingress-values.yaml
charts/locust/ci/with-worker-hpa-values.yaml
charts/locust/locustfiles/example/main.py
charts/locust/templates/NOTES.txt
charts/locust/templates/_helpers.tpl
charts/locust/templates/configmap-lib.yaml
charts/locust/templates/configmap-locustfile.yaml
charts/locust/templates/master/deployment.yaml
charts/locust/templates/master/ingress.yaml
charts/locust/templates/master/sa.yaml
charts/locust/templates/master/service.yaml
charts/locust/templates/worker/deployment.yaml
charts/locust/templates/worker/hpa.yaml
charts/locust/templates/worker/sa.yaml
charts/locust/values.yaml

This adds the initial Locust chart.

[locust] initial commit :tada:

---

charts/cronjob/.helmignore
charts/cronjob/Chart.lock
charts/cronjob/Chart.yaml
charts/cronjob/README.md
charts/cronjob/ci/default-values.yaml
charts/cronjob/ci/with-custom-image-values.yaml
charts/cronjob/ci/with-envvars-values.yaml
charts/cronjob/ci/with-multiple-values.yaml
charts/cronjob/ci/with-postgresql-values.yaml
charts/cronjob/ci/with-redis-values.yaml
charts/cronjob/templates/_helpers.tpl
charts/cronjob/templates/cronjob.yaml
charts/cronjob/templates/postgresql/wait-for-postgresql.yaml
charts/cronjob/templates/redis/wait-for-redis.yaml
charts/cronjob/values.yaml

This adds the `cronjob` Helm chart.

[cronjob] initial release :tada:

---

charts/cronjob/Chart.lock
charts/cronjob/Chart.yaml
charts/cronjob/values.yaml

- Bump `postgresql` from 10.6.0 to 10.9.1.
- Bump `redis` from 14.7.2 to 14.8.8.

[cronjob] update dependencies

---

charts/golang/Chart.yaml
charts/golang/templates/deployment.yaml

Signed-off-by: Andrew Ellis <awellis89@gmail.com>

[golang] add missing quotes for multi-line values

---

charts/golang/Chart.yaml
charts/golang/values.yaml

Updating the service account example to use the right project ID.

chore(golang): update sa example

---

charts/golang/Chart.yaml
charts/golang/ci/with-extra-volumes.yaml
charts/golang/templates/deployment.yaml
charts/golang/values.yaml

Adds two arrays to allow passing in additional volume and volumeMount
definitions to allow for mounting configmaps and secrets as volumes, for
example

feat(golang): Add extraVolumes, extraVolumeMounts

---

.github/workflows/release.yml
charts/golang/Chart.yaml
charts/golang/templates/deployment.yaml
charts/golang/values.yaml

This adds the `healthPort` configuration parameter. I also updated the CI workflow for the release process to use the latest process for chart releaser.

feat(golang): add healthPort configuration

---

charts/golang/Chart.lock
charts/golang/Chart.yaml

* Use latest common chart version

fix: use latest common chart

---

charts/golang/Chart.yaml
charts/golang/ci/with-vault-values.yaml
charts/golang/templates/deployment.yaml
charts/golang/values.yaml

- Set `ENV` based on the `.Values.fluidtruck.env` value.
- Set `NEW_RELIC_APP_NAME` based on the `.Values.fluidtruck.env` and `.Release.Name` values.
- Inject `newrelic`, `.env.shared`, and `.env` automatically if `.values.vault.enabled=true`.

feat(golang): introduce new vault api

---

charts/cronjob/Chart.lock
charts/cronjob/Chart.yaml
charts/cronjob/ci/with-postgresql-values.yaml
charts/cronjob/ci/with-redis-values.yaml
charts/cronjob/ci/with-sa-values.yaml
charts/cronjob/ci/with-vault-values.yaml
charts/cronjob/templates/cronjob.yaml
charts/cronjob/templates/postgresql/wait-for-postgresql.yaml
charts/cronjob/templates/redis/wait-for-redis.yaml
charts/cronjob/templates/sa.yaml
charts/cronjob/values.yaml

This adds support for Vault to the cronjob chart. It also adds various updates we've made to golang.

feat(cronjob): add vault support

---

charts/cronjob/Chart.yaml
charts/cronjob/templates/cronjob.yaml
charts/cronjob/values.yaml

* Change default cronjob schedule from every 1 minute, to every 60 minutes
* Change default cronjob concurrency policy from "Allow" to "Replace" - https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy

fix: change default cronjob schedule

---

charts/python/.helmignore
charts/python/Chart.lock
charts/python/Chart.yaml
charts/python/README.md
charts/python/ci/default-values.yaml
charts/python/ci/with-envvars-values.yaml
charts/python/ci/with-extra-application-ports-values.yaml.yaml
charts/python/ci/with-extra-volumes.yaml
charts/python/ci/with-hpa-values.yaml
charts/python/ci/with-sa-values.yaml
charts/python/ci/with-vault-values.yaml
charts/python/templates/NOTES.txt
charts/python/templates/_helpers.tpl
charts/python/templates/deployment.yaml
charts/python/templates/hpa.yaml
charts/python/templates/sa.yaml
charts/python/templates/service.yaml
charts/python/values.yaml

This adds the `fluidtruck/python` chart.

feat: add python chart (DO-222)

---

charts/common/Chart.yaml
charts/common/templates/_annotations.tpl

As per https://fluidtruck.atlassian.net/browse/DO-230.
* Add kubernetes.io/change-cause annotation to deployments

feat: add kubernetes.io/change-cause

---

.github/settings.yml
charts/api-gateway/.helmignore
charts/api-gateway/Chart.lock
charts/api-gateway/Chart.yaml
charts/api-gateway/README.md
charts/api-gateway/ci/default-values.yaml
charts/api-gateway/ci/with-vault-values.yaml
charts/api-gateway/templates/NOTES.txt
charts/api-gateway/templates/certificate.yaml
charts/api-gateway/templates/host.yaml
charts/api-gateway/templates/mapping.yaml
charts/api-gateway/values.yaml

feat: api-gateway helm chart

---

charts/api-gateway/Chart.yaml
charts/api-gateway/templates/mapping.yaml
charts/golang/Chart.yaml
charts/golang/templates/mapping.yaml
charts/golang/templates/tlscontext.yaml
charts/golang/values.yaml

* Add mapping for the service at the api endoint
* Example:  https://api.stage.fluidtruck.io/go-demo

feat: add gateway mapping

---

charts/golang/Chart.yaml
charts/golang/templates/mapping.yaml

* Add missing trailing slash to the prefix

fix: add trailing slash

---

.github/ct-install.yaml
.github/ct-lint.yaml
charts/golang/Chart.lock
charts/golang/Chart.yaml
charts/golang/templates/deployment.yaml
charts/golang/templates/dopplersecret.yaml
charts/golang/values.yaml

DARC-135.
* Add doppler integration for secrets management

feat: doppler

---

.github/workflows/release.yml

* Add missing bitnami-full repo for release - https://github.com/bitnami/charts/issues/10833

fix: add bitnami-full repo

---

charts/golang/Chart.lock
charts/golang/Chart.yaml
charts/golang/templates/deployment.yaml

fix: doppler reload

---

charts/dotnet/Chart.yaml
charts/dotnet/templates/_helpers.tpl
charts/dotnet/templates/deployment.yaml
charts/dotnet/templates/redis/wait-for-redis.yaml
charts/dotnet/templates/service.yaml
charts/dotnet/values.yaml

As per PLAT-283.
* Add redis to dotnet helm chart

ci: dotnet workflow

---

.github/settings.yml

[PLAT-199](https://fluidtruck.atlassian.net/browse/PLAT-199)
* Enable dependabot settings, which will do weekly dependency scans for:
* docker
* github-actions
* go
* The PRs created by dependabot will be appropriately labelled
---
* Also modify settings.yml for consistency
[PLAT-199]: https://fluidtruck.atlassian.net/browse/PLAT-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: enable dependabot checks

---

charts/dotnet/Chart.yaml
charts/dotnet/ci/with-ingress-values.yaml
charts/dotnet/ci/with-redis-values.yaml
charts/dotnet/templates/NOTES.txt
charts/dotnet/templates/_helpers.tpl
charts/dotnet/templates/ingress.yaml
charts/dotnet/templates/tlscontext.yaml
charts/dotnet/values.yaml

* Add ingress to dotnet helm chart

feat: add ingress to dotnet chart
