fluidtruck/helm-charts

charts/common/Chart.yaml, charts/common/templates/_capabilities.tpl
This adds the ability to do the following for `kind: CronJob`:
```
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
```
=> [common] add cronjob apiVersion

charts/golang/Chart.yaml, charts/golang/templates/frontendconfig-force-https.yaml, charts/golang/templates/ingress.yaml
When setting up our single service repos on stage we want to generate a single certificate that serves the following hosts:
- `{namespace}.fluidtruck.io`
- `*.{namespace}.fluidtruck.io`
To accomplish this, the pipeline will use the following ingress configs:
**PR:**
```
ingress:
enabled: true
hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}.fluidtruck.io"
extraTls:
- hosts:
- "{{ .Release.Namespace }}.fluidtruck.io"
- "*.{{ .Release.Namespace }}.fluidtruck.io"
secretName: "{{ .Release.Namespace }}-tls"
```
**Stage:**
```
ingress:
enabled: true
hostname: "stage.{{ .Release.Namespace }}.fluidtruck.io"
extraTls:
- hosts:
- "{{ .Release.Namespace }}.fluidtruck.io"
- "*.{{ .Release.Namespace }}.fluidtruck.io"
secretName: "{{ .Release.Namespace }}-tls"
```
**Prod:**
```
ingress:
enabled: …
```
=> [golang] check for extra tls

charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml, charts/golang/values.yaml
Updates helm chart to allow multiline templates and updates the example
to point to a more likely example secret path, and a template that can
take any number of env vars contained in the `env` secret and render
them appropriately.
=> [golang] fixes to allow for better env templating

charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml, charts/golang/values.yaml
Under the hood, our developer's microservices will be using Port 8090 from their containers to serve gRPC, and port 8080 to serve health checks. So we can remove one more configuration requirement (`applicationPort`) from their end, we will now default to 8090.
In doing so, I created a new container port called health, which exposes 8080 specifically for their readiness and liveness checks.
=> [golang] default to 8090

charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml, charts/golang/values.yaml
This will default to using `.Release.Namespace`, but can be overridden.
=> [golang] use namespace for vault.role

charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml, charts/golang/templates/sa.yaml
Fixes a mismatch between the k8s SA name and the bound SA that's created
by the Vault scaffolder action.
=> [golang] Fix mismatched service account names

charts/golang/Chart.yaml, charts/golang/values.yaml
We've opted for a single key-value store per-service instead of a
key-value store per environment, update the examples to match.
=> [golang] Fix example Vault paths

charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml, charts/golang/templates/sa.yaml
Reverts the change to SA naming convention to avoid clashing names in
staging and instead setting Vault to accept any kubernetes service
account name in the auth method.
=> [golang] Revert change to SA naming

.github/settings.yml, charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml
I noticed your PR fluidtruck/backstage#78 and realized the annotation being deployed on trip-scorer was missing `export`.
=> [golang] add missing export

charts/golang/Chart.yaml, charts/golang/ci/with-extra-application-ports-values.yaml.yaml, charts/golang/templates/_helpers.tpl, charts/golang/templates/deployment.yaml, charts/golang/values.yaml
This adds the `extraApplicationPorts` property. This allows us to define extra ports on the container. This is useful for DevSpace and enabling the `2345` debug port for Delve.
=> [golang] add extraApplicationPorts

charts/golang/Chart.yaml, charts/golang/templates/service.yaml
For our legacy cluster, we need to support `8090` on the service as well. We can remove this once all services are migrated and there are no more references to `8090` in ConfigMap/EnvVar definitions.
=> feat(golang): add http-legacy service port

charts/golang/Chart.yaml, charts/golang/templates/service.yaml
This was discovered by trying to upgrade `legacy-apps-stage` -> `telematics`. Previously, the service used [`type: NodePort`](https://github.com/fluidshare/telematics-domain/blob/main/telematics/chart/stage.yaml#L9-L10). By setting `type: ClusterIP`, we were getting the following error:
```
Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: cannot patch “telematics-golang” with kind Service: Service “telematics-golang” is invalid: spec.ports[1].nodePort: Forbidden: may not be used when `type` is ‘ClusterIP’: release telematics failed: timed out waiting for the condition
```
This ensures that `nodePort: null` is set under this circumstance. This allows the service to flip from `NodePort` to `ClusterIP` with no issue.
=> fix(golang): use null nodePort when using ClusterIP

charts/golang/Chart.yaml, charts/golang/templates/ingress.yaml, charts/golang/values.yaml
This adds `ingressClass` support to `golang`. Defaulted to `nginx`. If set to `false`, this can be disabled and will use the cluster's default Ingress.
=> feat(golang): add ingressClass support

charts/golang/Chart.yaml, charts/golang/ci/with-ingress-wildcard-values.yaml, charts/golang/templates/NOTES.txt, charts/golang/templates/_helpers.tpl, charts/golang/templates/deployment.yaml, charts/golang/templates/frontendconfig-force-https.yaml, charts/golang/templates/ingress.yaml, charts/golang/values.yaml
This PR was originally for External DNS, but I feel the API for this new implementation is a little easier to manage down in the dev chart values files; as we control fancy structure here in the chart.
By using the `domain` key, we will automatically piece together a URL based on the `.Release.Name` and `.Release.Namespace`values given to the chart; suffixed with the set `domain`.
```yaml
ingress:
enabled: true
domain: fluiddev.io
tls:
enabled: true
issuer: letsencrypt-production
```
Assuming you run `helm install my-feature fluidtruck/golang --namespace my-service -f ./values.yaml` you will get the following results:
- `my-feature.my-service.fluiddev.io`
- `*.my-service.fluiddev.io`
Instead of providing `domain`, you can provide `hostname` which is more declarative. This will force the …
=> feat(golang): improve ingress support

charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml, charts/golang/values.yaml
Reverts fluidtruck/helm-charts#27
=> fix: revert "fix ports in golang chart's probes"

charts/golang/Chart.yaml, charts/golang/templates/sa.yaml, charts/golang/values.yaml
In order to enable Workload Identity binding to GCP service accounts, we
need to expose adding custom annotations to the service account we
create for Vault reasons
[Relevant GCP docs](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)
=> feat: add Service Account annotations

charts/golang/Chart.yaml, charts/golang/ci/with-swagger-values.yaml, charts/golang/templates/ingress.yaml, charts/golang/values.yaml
This swaps Swagger to use the `/docs` path for services. This should resolve the TLS issues we're seeing with the wildcard certs and normal certs being in the same namespace.
=> feat(golang): use docs path

charts/golang/Chart.yaml, charts/golang/ci/with-ingress-and-devMode.yaml, charts/golang/ci/with-ingress-values.yaml, charts/golang/ci/with-swagger-values.yaml, charts/golang/templates/NOTES.txt, charts/golang/templates/_helpers.tpl, charts/golang/templates/deployment.yaml, charts/golang/templates/ingress.yaml, charts/golang/templates/service.yaml, charts/golang/values.yaml
As I was working through Swagger, I also discovered our TLS was going to have major issues once we go back to a single domain. With this approach, we will generate a _single_ certificate per service and it will handle the PRs + Static hosts, and is easier to configure on the dev side. For example:
**dev/stage:**
```yaml
ingress:
enabled: true
tls:
enabled: true
issuer: "letsencrypt-production"
swagger:
enabled: true
```
Then using the following, you can install the chart:
```sh
helm upgrade ${RELEASE_NAME} ./charts/golang \
--install \
--namespace backend \
--create-namespace \
--set ingress.devMode="true" \
--set ingress.domain="${{ matrix.service }}.stage.fluidtruck.io" \
helm upgrade api-platform ./charts/golang \
--install \
--namespace backend \
--create-namespace \
--set …
```
=> feat(golang): simplify tls generation

charts/golang/Chart.yaml, charts/golang/ci/with-sa-values.yaml, charts/golang/templates/_helpers.tpl, charts/golang/templates/deployment.yaml, charts/golang/templates/sa.yaml, charts/golang/values.yaml
This adds the ability to create a service account. If disabled, we will use the `default`. This allows our default SA for a tenant to have basic workload identity permissions.
=> feat(golang): add serviceAccount config

charts/cronjob/Chart.yaml, charts/cronjob/templates/cronjob.yaml
Names need to be 52 chars or less.
```
Error: release reservation-section-cronjob failed, and has been uninstalled due to atomic being set: CronJob.batch "reservation-section-cronjob-reservation-section-cronjob" is invalid: metadata.name: Invalid value: "reservation-section-cronjob-reservation-section-cronjob": must be no more than 52 characters
```
=> fix(cronjob): trunc cronjob name to 52 chars

charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml, charts/golang/values.yaml
Allow the devs to override readiness and liveness probe ports. This is helpful for fluidshare/plasma's scheduler service.
=> feat(golang): add readiness and liveness probe port

charts/cronjob/Chart.yaml, charts/cronjob/templates/_helpers.tpl, charts/cronjob/templates/cronjob.yaml, charts/cronjob/templates/sa.yaml, charts/cronjob/values.yaml
Adds an optional service account creation to CronJob helm chart. This is
necessary to use Workload Identity to bind GCP credentials for a CronJob
to access.
=> feat: Add optional k8s SA to CronJob chart

charts/golang/Chart.lock, charts/golang/Chart.yaml, charts/golang/templates/_helpers.tpl, charts/golang/templates/deployment.yaml, charts/golang/templates/hpa.yaml, charts/golang/templates/ingress.yaml, charts/golang/templates/postgresql/wait-for-postgresql.yaml, charts/golang/templates/redis/wait-for-redis.yaml, charts/golang/templates/sa.yaml, charts/golang/templates/service.yaml, charts/golang/values.yaml
As per https://fluidtruck.atlassian.net/browse/DO-154.
Add K8S and GitHub labels to objects. This should allow filtering/identification as much in K8S as in NewRelic.
Labels:
* fluidtruck.io/app
* fluidtruck.io/env
* fluidtruck.io/team
* github.com/branch
* github.com/pull-request
* github.com/repository
* github.com/release
Annotations:
* github.com/repository-url
* github.com/pull-request-url
* github.com/pull-request-owner
* github.com/release-url
---
PostgreSQL:
* Upgrade postgresql chart version, previous version no longer available
* Chart version 11.1.28 = PostgreSQL 14.2, which is what we've starting going to in stage/prod
* Going to PostgreSQL 14.x introduces some changes, as noted here - https://github.com/bitnami/charts/issues/8900#issuecomment-1029710668
* Auth-related helm …
=> feat(golang): add labels

charts/cronjob/Chart.yaml, charts/cronjob/templates/cronjob.yaml
Need to use `$top` to prevent this error:
```shell
Error: template: cronjob/templates/cronjob.yaml:15:8: executing "cronjob/templates/cronjob.yaml" at <include "common.labels.fluidtruck" .>: error calling include: template: cronjob/charts/common/templates/_labels.tpl:16:29: executing "common.labels.fluidtruck" at <.Values.fluidtruck.app>: nil pointer evaluating interface ***.fluidtruck
```
=> fix(cronjob): use $top

charts/cronjob/Chart.yaml, charts/cronjob/templates/cronjob.yaml, charts/golang/Chart.yaml, charts/golang/templates/deployment.yaml
Missing `export` causes the `source` calls to these two files to not actually load the contents into the environment.
=> fix(golang,cronjob): add export to shared and env

charts/golang/Chart.yaml, charts/golang/ci/with-extra-application-ports-values.yaml.yaml, charts/golang/templates/deployment.yaml, charts/golang/templates/service.yaml, charts/golang/values.yaml
BREAKING CHANGE: `extraApplicationPorts` is now an array
---
While setting up Telepresence, I discovered that we need to leverage the [`appProtocol`](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol) directive for gRPC services. Since our Golang chart is 99.99% for gRPC I defaulted to the `grpc` protocol. This was documented on the Telepresence community [here](https://datawire-oss.slack.com/archives/CAUBBJSQZ/p1666257430302089?thread_ts=1666099819.269849&cid=CAUBBJSQZ).
This can be set to `http` declaratively for services like go-demo and api-*.
=> feat(golang)!: use an array for extraApplicationPorts

charts/golang/Chart.yaml, charts/golang/ci/with-hpa-values.yaml, charts/golang/ci/with-pdb.yaml, charts/golang/templates/pdb.yaml, charts/golang/values.yaml
This adds the Pod Disruption Budget configuration to Golang. This is recommended to use in the following two ways:
```yaml
replicaCount: 2
podDisruptionBudget:
enabled: true
minAvailable: 1
hpa:
enabled: true
minReplicas: 2
maxReplicas: 5
podDisruptionBudget:
enabled: true
minAvailable: 2
```
I wanted to enable automatic `minAvailable` defined by the value of `replicaCount` or `hpa.minReplicas`. However, the `mul` and `div` methods return `0`... Maybe we can improve this later. But for now, we'll just need to be declarative.
```yaml
minAvailable: {{ .Values.replicaCount | int | mul 0.5 | int }} # returns 0 for any odd value given to replicaCount
```
=> feat(golang): add pdb

charts/cronjob/Chart.lock, charts/cronjob/Chart.yaml, charts/cronjob/ci/with-vault-values.yaml, charts/cronjob/templates/cronjob.yaml, charts/cronjob/values.yaml, charts/golang/Chart.lock, charts/golang/Chart.yaml, charts/golang/ci/with-vault-values.yaml, charts/golang/templates/deployment.yaml, charts/golang/values.yaml
This consumes the new Vault common helpers. The following scenarios are now possible:
By defining the following:
```yaml
fluidtruck:
env: stage
vault:
auth:
department: engineering
team: backend
service: ''
```
The following will be generated:
- Role: `engineering-backend-stage`
- Paths: `engineering/backend/shared`, `engineering/backend/stage`
By defining the following:
```yaml
fluidtruck:
env: stage
vault:
auth:
department: engineering
team: backend
service: event-store
```
The following will be generated:
- Role: `engineering-backend-event-store-stage`
- Paths: `engineering/backend/event-store/shared`, `engineering/backend/event-store/stage`
=> feat(cronjob,golang): add service to vault.auth

charts/golang/Chart.lock, charts/golang/Chart.yaml
* Upgrade version of used redis chart in order to reduce number of security vulnerabilities present on the current cluster
* Version 17.x of the helm chart brings redis from version 6.2 to 7.0 - https://github.com/bitnami/charts/tree/main/bitnami/redis#to-1700
=> chore(golang): upgrade redis
